name: Artifact Build

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # - name: Run Gradle command
      #   uses: Raul6469/android-gradle-action@2.0.0
      #   with:
      #     script: assembleRelease
      #     android-license: ${{ secrets.ANDROID_LICENCE }}
      - name: Add Android SDK tools to PATH
        run: export PATH="$PATH:/usr/local/lib/android/sdk/cmdline-tools/7.0/bin"
      # - run: yes | sdkmanager --licenses
      - name: Set up signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > signing-key.jks
      # - name: Build APK
      #   run: ./gradlew assembleRelease
      - uses: burrunan/gradle-cache-action@v1
        name: Build NativeAlpha
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        with:
          arguments: assembleRelease
          properties: org.gradle.caching=true
      - uses: actions/upload-artifact@v3
        with:
          name: NativeAlpha
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/release/
      - name: Upload (file inside) Folder to file.io 
        run: |
          URL="https://file.io"
          DEFAULT_EXPIRE="14d" # Default to 14 days

          EXPIRE=${EXPIRE:-$DEFAULT_EXPIRE}

          if [ ! -d "$FOLDER" ]; then
              echo "Folder ${FOLDER} not found"
              exit 1
          fi

          for FILE in "$FOLDER"/*; do
              if [ -f "$FILE" ]; then
                  RESPONSE=$(curl -# -F "file=@${FILE}" "${URL}/?expires=${EXPIRE}")
                  echo "Uploaded ${FILE}: ${RESPONSE}"
              fi
          done
        env:
          FOLDER: ${{ github.workspace }}/app/build/outputs/apk/release/
          EXPIRE: 1w

            
