name: Artifact Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    # - name: set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: temurin
    #     java-version: 11
    #     cache: gradle
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        script: assembleRelease
        android-license: ${{ secrets.ANDROID_LICENCE }}
    - uses: actions/upload-artifact@v2
      with:
        name: NativeAlpha
        path: |
          app/build/outputs/apk/release/*.apk
