name: Artifact Build

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # - name: Run Gradle command
      #   uses: Raul6469/android-gradle-action@2.0.0
      #   with:
      #     script: assembleRelease
      #     android-license: ${{ secrets.ANDROID_LICENCE }}
      - run: yes | sdkmanager --licenses
      - name: Set up signing key
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > signing-key.jks
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: NativeAlpha
          path: |
            app/build/outputs/apk/release/*.apk
            
